[libraries]
commonsCodec = {module = 'commons-codec:commons-codec', version = '1.17.1'}
commonsIo = { module = 'commons-io:commons-io', version = '2.6' }
guava = { module = "com.google.guava:guava", version = "31.1-jre" }
gson = { module = 'com.google.code.gson:gson', version = '2.11.0' }
junitJupiterCore = { module = "org.junit.jupiter:junit-jupiter", version = "5.9.3" }
spotless = { module = 'com.diffplug.spotless:spotless-plugin-gradle', version = '6.22.0' }
kotlinJvmPlugin = {module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version = '1.9.21'}
