[versions]
jupiter-version = "5.9.3"


[libraries]
commonsIo = { module = 'commons-io:commons-io', version = '2.6' }
guava = { module = "com.google.guava:guava", version = "31.1-jre" }
junitJupiterCore = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter-version" }
